In [1]:
from IPython.display import display, HTML
display(HTML('<style>.container {width: 100%}</style>'))

## Numpy 특징
- ### Numerical Python의 약자
- ### 고성능 과학 계산용 패키지로 강력한 N차원 배열 객체
- ### 범용적 데이터 처리에 사용 가능한 다차원 컨테이너
- ### 정교한 브로드캐스팅(broadcasting) 기능
- ### 파이썬의 자료형 list와 비슷하지만, 더 빠르고 메모리를 효율적으로 관리
- ### 반복문 없이 데이터 배열에 대한 처리를 지원하여 빠르고 편리
- ### 데이터 과학 도구에 대한 생태계의 핵심을 이루고 있음

In [2]:
import numpy as np

In [3]:
np.__version__

'1.20.3'

In [4]:
a1 = np.array([1, 2, 3, 4, 5])
print(a1)

[1 2 3 4 5]


In [5]:
print(type(a1)) # ndarray : N-Dimension Array

<class 'numpy.ndarray'>


In [6]:
print(a1.shape)

(5,)


In [7]:
print(a1[0], a1[1], a1[2], a1[3], a1[4])

1 2 3 4 5


In [8]:
a1[0] = 10
a1[1] = 20

print(a1[0], a1[1], a1[2], a1[3], a1[4])

10 20 3 4 5


In [9]:
a2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a2)
print(a2.shape)
print(a2[0, 0], a2[1, 1],a2[2, 1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
1 5 8


In [10]:
a3 = np.array([[[0, 1, 2],[0, 1, 2],[0, 1, 2]],[[0, 1, 2],[0, 1, 2],[0, 1, 2]], [[0, 1, 2],[0, 1, 2],[0, 1, 2]]])
print(a3)
print(a3.shape)
print(a3[0, 0, 0], a3[1, 1, 1],a3[2, 1, 2])

[[[0 1 2]
  [0 1 2]
  [0 1 2]]

 [[0 1 2]
  [0 1 2]
  [0 1 2]]

 [[0 1 2]
  [0 1 2]
  [0 1 2]]]
(3, 3, 3)
0 1 2


## 배열 생성 및 초기화
- ### zeros() : 모든 요소를 0으로 초기화
- ### ones() : 모든 요소를 1으로 초기화
- ### full() : 모든 요소를 지정한 값으로 초기화
- ### eys() : 단위행렬(Identity matrix) 생성
- ### tri() : 삼각행렬 생성
- ### empty() : 초기화 하지 않은 행렬 생성 (★ 주의 필요)
- ### \_like() : 지정된 배열과 shape가 같은 행렬 생성

In [11]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
print(np.ones(10))
print('---')
print(np.ones((10,5)))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
---
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [13]:
np.full(10, 1.5)

array([1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5])

In [14]:
np.full((3,3), 1.5)

array([[1.5, 1.5, 1.5],
       [1.5, 1.5, 1.5],
       [1.5, 1.5, 1.5]])

In [15]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
np.tri(4)

array([[1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 1.]])

In [17]:
np.empty(5) # 여기 숫자(예, 1.) 은 내가 정한게 아님

array([1., 1., 1., 1., 1.])

In [18]:
np.zeros_like(a2)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [19]:
np.ones_like(a2)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [20]:
np.full_like(a2, 10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

## 생성한 값으로 배열 생성
- ### np.arange() : 정수 범위로 배열 생성
- ### np.linspace() : 범위 내에서 균등 간격의 배열 생성

## 랜덤 값으로 배열 생성
- ### seed() : 난수 발생을 위한 seed 지정
- ### permutation() : 순서를 임의로 바꾸거나 임의의 순환 반환
- ### shuffle() : 리스트나 배열의 순서를 뒤섞음
- ### random() : 랜덤한 수의 배열을 생성
- ### rand() : 균등 분포에서 표본 추출
- ### randint() : 주어진 최소/최대 범위의 난수 추출
- ### randn() : 평균 0, 표준편자 1 인 정규분포의 표본 추출
- ### binomial() : 이항 분포에서 표본 추출
- ### normal() : 정규 분포(가우시안)에서 표본 추출
- ### beta() : 베타 분포에서 표본 추출
- ### chisquare() : 카이제곱 분포에서 표본 추출
- ### gamma() : 감마 분포에서 표본 추출
- ### uniform() : 균등(0,1) 분포에서 표본 추출

In [21]:
2147483648*2

4294967296

In [22]:
4294967296*2

8589934592

In [23]:
np.exp2(16)

65536.0

In [24]:
np.exp2(32)

4294967296.0

In [25]:
print(np.exp2(64))

1.8446744073709552e+19


## Numpy 표준 데이터 타입
- ### bool_ : 바이트로 저장된 불리언(Boolean)으로 True 또는 False 값을 가짐
- ### int_ : 기본 정수(Integer) 타입
- ### intc : C언어에서 사용되는 int와 동일 (일반적으로 int32, int64)
- ### intp : 인덱싱에서 사용되는 정수 (C 언어에서 ssize_t, 일반적으로 int32, int64)
- ### int8 : 바이트(Byte) (-128 ~ 127)
- ### int16 : 정수 (-32768 ~ 32767)
- ### int32 : 정수 (-2147483648 ~ 2147483647)
- ### int64 : 정수 (... ~ ...)
- ### uint8 : 부호 없는 정수 (0 ~ 255)
- ### uint16 : 부호 없는 정수 (0 ~ 65535)
- ### uint32 : 부호 없는 정수 (0 ~ 4294967295)
- ### uint64 : 부호 없는 정수 (0 ~ ...)
- ### float16 : 반정밀 부동 소수점 (Half precision float), 부호 비트, 5비트 지수, 10비트 가수
- ### float32 : 단정밀 부동 소수점 (Single precision float), 부호 비트, 8비트 지수, 32비트 가수
- ### float64 : 배정밀 부동 소수점 (Half precision float), 부호 비트, 11비트 지수, 52비트 가수
- ### float_ : float64를 줄여서 표현
- ### complex64 : 복소수(Complex number), 두 개의 32비트 부동 소수점으로 표현
- ### complex128 : 복수소, 두 개의 64비트 부동 소수점으로 표현

In [26]:
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

## 날짜/시간 배열 생성
- ### Y     연
- ### M     월
- ### W     주
- ### D     일
- ### h     시
- ### m     분
- ### s     초
- ### ms     밀리초
- ### us     마이크로초
- ### ps     나노초
- ### fs     피코초
- ### as     아토초


In [27]:
date = np.array('2021-01-01', dtype=np.datetime64)

In [28]:
date + np.arange(12)

array(['2021-01-01', '2021-01-02', '2021-01-03', '2021-01-04',
       '2021-01-05', '2021-01-06', '2021-01-07', '2021-01-08',
       '2021-01-09', '2021-01-10', '2021-01-11', '2021-01-12'],
      dtype='datetime64[D]')

In [29]:
datetime = np.datetime64('2021-06-01 12:00')
datetime

numpy.datetime64('2021-06-01T12:00')

In [30]:
datetime = np.datetime64('2021-06-01 12:00:12.34', 'ns')
datetime

numpy.datetime64('2021-06-01T12:00:12.340000000')

## 배열 조회
- ### 배열 속성 정보

In [31]:
def array_info(array):
    print(array)
    print('ndim: ', array.ndim)
    print('shape: ', array.shape)
    print('dtype: ', array.dtype)
    print('size: ', array.size)
    print('itemsize: ', array.itemsize) # 4는 8 bytes 를 의미
    print('nbytes: ', array.nbytes)     # 8 bytes * 4개 items를 의미
    print('strides: ', array.strides)

In [32]:
array_info(a1)

[10 20  3  4  5]
ndim:  1
shape:  (5,)
dtype:  int32
size:  5
itemsize:  4
nbytes:  20
strides:  (4,)


In [33]:
array_info(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
ndim:  2
shape:  (3, 3)
dtype:  int32
size:  9
itemsize:  4
nbytes:  36
strides:  (12, 4)


In [34]:
array_info(a3)

[[[0 1 2]
  [0 1 2]
  [0 1 2]]

 [[0 1 2]
  [0 1 2]
  [0 1 2]]

 [[0 1 2]
  [0 1 2]
  [0 1 2]]]
ndim:  3
shape:  (3, 3, 3)
dtype:  int32
size:  27
itemsize:  4
nbytes:  108
strides:  (36, 12, 4)


## 인덱싱(Indexing)

In [35]:
print(a1)
print(a1[0])
print(a1[1])
print(a1[-1])
print(a1[-2])

[10 20  3  4  5]
10
20
5
4


In [36]:
print(a2)
print(a2[0, 0])
print(a2[1, 1])
print(a2[-1, 1])
print(a2[-1, 1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
5
8
8


## 슬라이싱(Slicing)
- ### 슬라이싱 구문: a[start:stop:step]
- ### 기본값: start=0, stop=ndim, step=1

In [37]:
print(a1)
print(a1[0:4])
print(a1[0:4:2])

[10 20  3  4  5]
[10 20  3  4]
[10  3]


## 불리언 인덱싱(Boolean Indexing)
- ### 배열 각 요소의 선택 여부를 불리언(Tru or False)로 지정
- ### True 값인 인덱스의 값만 조회

In [38]:
print(a1)
bi = [False, True, True, False, True]
print(a1[bi])

[10 20  3  4  5]
[20  3  5]


In [39]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
bi = np.random.randint(0, 2, (3,3), dtype=bool)
print(bi)
print(a2[bi])

[[ True False  True]
 [ True  True  True]
 [False False False]]
[1 3 4 5 6]


## 팬시 인덱싱 (Fancy Indexing)

In [41]:
print(a1)
print(a1[0], a1[2])
ind = [0, 2]
print(a1[ind])
ind = np.array([[0, 1], 
               [2, 0]])
print(a1[ind])   #1차원 배열인데, 2차원 인덱싱을 주었더니 결과는 2차원으로 반환

[10 20  3  4  5]
10 3
[10  3]
[[10 20]
 [ 3 10]]


In [42]:
print(a2)
row = np.array([0, 2])
col = np.array([1, 2])
print(a2[row, col]) # a2[0,2], a2[2,2]

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 9]


## 배열 값 삽입/수정/삭제/복사
- ### 배열 값 삽입
   - insert() : 배열의 특정 위치에 값 삽입
   - axis를 지정하지 않으면 1차원 배열로 변환
   - 추가할 방향을 axis로 지정
   - 원본 배열 변경없이 새로운 배열 반환

In [43]:
print(a1)
b1 = np.insert(a1, 0, 4)
print(b1)
print(a1)
c1 = np.insert(a1, 2, 5)
print(c1)

[10 20  3  4  5]
[ 4 10 20  3  4  5]
[10 20  3  4  5]
[10 20  5  3  4  5]


In [44]:
print(a2)
b2 = np.insert(a2, 1, 10, axis=0)
print(b2)
c2 = np.insert(a2, 1, 10, axis=1)
print(c2)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [10 10 10]
 [ 4  5  6]
 [ 7  8  9]]
[[ 1 10  2  3]
 [ 4 10  5  6]
 [ 7 10  8  9]]


- ### 배열 값 수정
   - 배열의 인덱싱으로 접근하여 값 수정

In [45]:
print(a1)
a1[0] = 1
a1[1] = 2
a1[2] = 3
print(a1)
a1[:1] = 9
print(a1)
i = np.array([1, 3, 4])
a1[i] = 0
print(a1)
a1[i] += 4
print(a1)

[10 20  3  4  5]
[1 2 3 4 5]
[9 2 3 4 5]
[9 0 3 0 0]
[9 4 3 4 4]


In [46]:
print(a2)
a2[0, 0] = 1
a2[1, 1] = 2
a2[2, 2] = 3
print(a2)
a2[0] = 1
print(a2)
a2[1:, 2] = 9
print(a2)

row = np.array([0, 1])
col = np.array([1, 2])
a2[row, col ] = 0
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 2 6]
 [7 8 3]]
[[1 1 1]
 [4 2 6]
 [7 8 3]]
[[1 1 1]
 [4 2 9]
 [7 8 9]]
[[1 0 1]
 [4 2 0]
 [7 8 9]]


- ## 배열 값 삭제
    - delete() : 배열의 특정 위치에 값 삭제
    - axis를 지정하지 않으면 1차원 배열로 변환
    - 삭제할 방향을 axis로 지정
    - 원본 배열 변경없이 새로운 배열 반환

In [47]:
print(a1)
b1 = np.delete(a1, 1)
print(b1)
print(a1)

[9 4 3 4 4]
[9 3 4 4]
[9 4 3 4 4]


In [48]:
print(a2)
b2 = np.delete(a2, 1, axis=0)
print(b2)
c2 = np.delete(a2, 1, axis=1)
print(c2)

[[1 0 1]
 [4 2 0]
 [7 8 9]]
[[1 0 1]
 [7 8 9]]
[[1 1]
 [4 0]
 [7 9]]


- ## 배열 복사
     - 리스트 자료형과 달리 배열의 슬라이스는 복사본이 아님

In [49]:
print(a2)
print(a2[:2, :2])
a2_sub = a2[:2, :2]
print(a2_sub)
a2_sub[:, 1] = 0
print(a2_sub)
print(a2)

[[1 0 1]
 [4 2 0]
 [7 8 9]]
[[1 0]
 [4 2]]
[[1 0]
 [4 2]]
[[1 0]
 [4 0]]
[[1 0 1]
 [4 0 0]
 [7 8 9]]


- ### copy(): 배열이나 하위 배열 내의 값을 <font color=red>명시적으로 복사</font>

In [50]:
print(a2)
a2_sub_copy = a2[:2, :2].copy()
print(a2_sub_copy)
a2_sub_copy[:, 1] = 1
print(a2_sub_copy)
print(a2)

[[1 0 1]
 [4 0 0]
 [7 8 9]]
[[1 0]
 [4 0]]
[[1 1]
 [4 1]]
[[1 0 1]
 [4 0 0]
 [7 8 9]]


## 배열 변환
- ### 배열 전치 및 축 변경

In [51]:
print(a2)
print(a2.T)
print()
print(a2.swapaxes(1, 0))

[[1 0 1]
 [4 0 0]
 [7 8 9]]
[[1 4 7]
 [0 0 8]
 [1 0 9]]

[[1 4 7]
 [0 0 8]
 [1 0 9]]


In [52]:
print(a3)
print(a3.swapaxes(0, 1))
print(a3.swapaxes(1, 2))

[[[0 1 2]
  [0 1 2]
  [0 1 2]]

 [[0 1 2]
  [0 1 2]
  [0 1 2]]

 [[0 1 2]
  [0 1 2]
  [0 1 2]]]
[[[0 1 2]
  [0 1 2]
  [0 1 2]]

 [[0 1 2]
  [0 1 2]
  [0 1 2]]

 [[0 1 2]
  [0 1 2]
  [0 1 2]]]
[[[0 0 0]
  [1 1 1]
  [2 2 2]]

 [[0 0 0]
  [1 1 1]
  [2 2 2]]

 [[0 0 0]
  [1 1 1]
  [2 2 2]]]


## 배열 재구조화
- ### reshape(): 배열의 형상을 변경

In [53]:
n1 = np.arange(1, 10)
print(n1)
print(n1.reshape(3,3))

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


- ### newaxis() : 새로운 

In [54]:
print(n1)
print(n1[np.newaxis, :5])
print(n1[:5, np.newaxis])

[1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


## 배열 크기 변경
- ### 배열 모양만 변경

In [55]:
n2 = np.random.randint(0, 10, (2,5))
print(n2)
n2.resize((5,2))
print(n2)

[[1 4 3 8 3]
 [0 9 5 8 8]]
[[1 4]
 [3 8]
 [3 0]
 [9 5]
 [8 8]]


- ### 배열 크기 증가
- ### 남은 공간은 0으로 채워짐

In [56]:
n2.resize((5,5))

In [57]:
print(n2)

[[1 4 3 8 3]
 [0 9 5 8 8]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


- ### 배열 크기 감소
- ### 남은 공간은 0으로 채워짐

In [58]:
n2.resize((3,3))
print(n2)

[[1 4 3]
 [8 3 0]
 [9 5 8]]


## 배열 추가
- ### append() : 배열의 끝에 추가

In [59]:
a2 = np.arange(1, 10).reshape(3,3)
print(a2)
b2 = np.arange(10, 19).reshape(3,3)
print(b2)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


- ### axis 지정이 없으면 1차원 배열 형태로 변형되어 결합

In [60]:
c2 = np.append(a2, b2)
print(c2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


- ### axis를 0으로 지정
- ### shape[0] 을 제외한 나머지 shape은 같아야 함

In [61]:
c2 = np.append(a2, b2, axis=0)
print(c2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


- ### asis를 1로 지정
- ### shpe[1]을 제외한 나머지 shape은 같아야 함

In [62]:
c2 = np.append(a2, b2, axis=1)
print(c2)

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


## 배열 연결
- ### concatenate() : 튜플이나 배열의 리스트를 인수로 사용해 배열 연결

In [63]:
a1 = np.array([1, 3, 5])
b1 = np.array([2, 4, 6])
np.concatenate([a1, b1])

array([1, 3, 5, 2, 4, 6])

In [64]:
c1 = np.array([7, 8, 9])
np.concatenate([a1, b1, c1])

array([1, 3, 5, 2, 4, 6, 7, 8, 9])

In [65]:
a2 = np.array([[1,2, 3], 
               [2, 4, 6]])
np.concatenate([a2, a2])

array([[1, 2, 3],
       [2, 4, 6],
       [1, 2, 3],
       [2, 4, 6]])

In [66]:
np.concatenate([a2, a2], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [2, 4, 6, 2, 4, 6]])

- ### vstack() : 수직 스택(vertical stack), 1차원으로 연결

In [67]:
np.vstack([a2, a2])

array([[1, 2, 3],
       [2, 4, 6],
       [1, 2, 3],
       [2, 4, 6]])

- ### hstack() : 수평 스택(horizontal stack), 2차원으로 연결

In [68]:
np.hstack([a2, a2])

array([[1, 2, 3, 1, 2, 3],
       [2, 4, 6, 2, 4, 6]])

- ### dstack() : 깊이 스택(depth stack), 3차원으로 연결

In [69]:
np.dstack([a2, a2])

array([[[1, 1],
        [2, 2],
        [3, 3]],

       [[2, 2],
        [4, 4],
        [6, 6]]])

- ### stack() : 새로운 차원으로 연결

In [70]:
np.stack([a2, a2])

array([[[1, 2, 3],
        [2, 4, 6]],

       [[1, 2, 3],
        [2, 4, 6]]])

## 배열 분할
- ### split() :. 배열 분할

In [71]:
a1 = np.arange(0, 10)
print(a1)

b1, c1 = np.split(a1, [5])
print(b1, c1)

b1, c1, d1, e1, f1 = np.split(a1, [2, 4, 6, 8])
print(b1, c1, d1, e1, f1)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4] [5 6 7 8 9]
[0 1] [2 3] [4 5] [6 7] [8 9]


- ### vsplit() : 수직 분할, 1차원으로 분할

In [72]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
b2, c2 = np.vsplit(a2, [2])
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]
[[7 8 9]]


- ### hsplit() : 수평 분할, 2차원으로 분할

In [73]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
b2, c2 = np.hsplit(a2, [2])
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]
 [7 8]]
[[3]
 [6]
 [9]]


- ### dsplit() : 깊이 분할, 3차원으로 분할

In [74]:
a3 = np.arange(1, 28).reshape(3, 3, 3)
print(a3)
b3, c3 = np.dsplit(a3, [2])
print(b3)
print(c3)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[[[ 1  2]
  [ 4  5]
  [ 7  8]]

 [[10 11]
  [13 14]
  [16 17]]

 [[19 20]
  [22 23]
  [25 26]]]
[[[ 3]
  [ 6]
  [ 9]]

 [[12]
  [15]
  [18]]

 [[21]
  [24]
  [27]]]


## 배열 연산
- ### Numpy의 배열 연산은 벡터화(vectorized) 연산을 사용
- ### 일반적으로 Numpy의 범용 함수(universal functions)를 통해 구현
- ### 배열 요소에 대한 반복적인 계산을 효율적으로 수행

### 브로드캐스팅(Broadcasting)

In [75]:
a1 = np.array([1, 2, 3])
b1 = np.array([[4], [5]])
print(a1)
print(b1)
print(a1 + b1)

[1 2 3]
[[4]
 [5]]
[[5 6 7]
 [6 7 8]]


## 산술 연산(Arithmetic Operators)
- '+'     np.add     덧셈
- '-'     np.substract 뺄셈
- '-'     np.negative  단향 음수
- '*'     np.multiply  곱셈
- '/'     np.divide    나눗셈
- '//'    np.floor_divide 나눗셈 내림
- '**'   np.power     지수연산
- '%'     np.mod     나머지 연산

In [76]:
a1 = np.arange(1, 10)
print(a1)
print(a1 +1)
print(np.add(a1, 10))
print(np.add(a1, -2))

print(np.subtract(a1, 10))
print(np.subtract(a1, -10))
print(-a1)
print(np.negative(a1))
print(a1*2)
print(np.multiply(a1, 2))
print(a1/2)
print(np.divide(a1, 2))
print(a1//2)
print(np.floor_divide(a1, 2))

print(a1**2)
print(np.power(a1, 2))

print(a1%2)
print(np.mod(a1, 2))

[1 2 3 4 5 6 7 8 9]
[ 2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19]
[-1  0  1  2  3  4  5  6  7]
[-9 -8 -7 -6 -5 -4 -3 -2 -1]
[11 12 13 14 15 16 17 18 19]
[-1 -2 -3 -4 -5 -6 -7 -8 -9]
[-1 -2 -3 -4 -5 -6 -7 -8 -9]
[ 2  4  6  8 10 12 14 16 18]
[ 2  4  6  8 10 12 14 16 18]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0 1 1 2 2 3 3 4 4]
[0 1 1 2 2 3 3 4 4]
[ 1  4  9 16 25 36 49 64 81]
[ 1  4  9 16 25 36 49 64 81]
[1 0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0 1]


## 절대값 함수 (Absolute Function)
- ### absolute(), abs(): 내장된 절대값 함수

In [77]:
a1 = np.random.randint(-10, 10, size=5)
print(a1)
print(np.absolute(a1))
print(np.abs(a1))

[3 7 4 5 9]
[3 7 4 5 9]
[3 7 4 5 9]


## 제곱/제곱근 함수
- ### squar(), sqrt() : 제곱, 제곱근 함수

In [78]:
a1 = np.random.randint(0, 20, size=5)
print(a1)
print(np.square(a1))
print(np.sqrt(a1))

[14  4  7  4 10]
[196  16  49  16 100]
[3.74165739 2.         2.64575131 2.         3.16227766]


- ### 지수와 로그함수 (Exponential and Log Function)

In [79]:
a1 = np.random.randint(0, 10, size= 5)
print(a1)
print(np.exp(a1))
print(np.exp2(a1))
print(np.power(a1, 2))

[8 0 0 0 1]
[2.98095799e+03 1.00000000e+00 1.00000000e+00 1.00000000e+00
 2.71828183e+00]
[256.   1.   1.   1.   2.]
[64  0  0  0  1]


In [80]:
print(a1)
print(np.log(a1))
print(np.log2(a1))
print(np.log10(a1))

[8 0 0 0 1]
[2.07944154       -inf       -inf       -inf 0.        ]
[  3. -inf -inf -inf   0.]
[0.90308999       -inf       -inf       -inf 0.        ]


C:\Users\Chulho Jung\AppData\Local\Temp\ipykernel_11668\1600939233.py:2: RuntimeWarning: divide by zero encountered in log
  print(np.log(a1))
C:\Users\Chulho Jung\AppData\Local\Temp\ipykernel_11668\1600939233.py:3: RuntimeWarning: divide by zero encountered in log2
  print(np.log2(a1))
C:\Users\Chulho Jung\AppData\Local\Temp\ipykernel_11668\1600939233.py:4: RuntimeWarning: divide by zero encountered in log10
  print(np.log10(a1))


## 삼각 함수(Trigonometrical Function)
- ### np.sin(array)  요소별 사인
- ### np.cos(array)  요소별 코사인
- ### np.tan(array)  요소별 탄젠트
- ### np.arcsin(array)  요소별 아크 사인
- ### np.arccos(array)  요소별 아크 코사인
- ### np.arctan(array)  요소별 아크 탄젠트
- ### np.arctan2(array1, array2)  요소별 아크 탄젠트 array1 / array2
- ### np.sinh(array)  요소별 하이퍼블럭 사인
- ### np.cosh(array)  요소별 하이퍼블럭 코사인
- ### np.tanh(array)  요소별 하이퍼블럭 탄젠트
- ### np.arcsinh(array)  요소별 하이퍼블럭 아크 사인
- ### np.arccosh(array)  요소별 하이퍼블럭 아크 코사인
- ### np.arctanh(array)  요소별 하이퍼블럭 아크 탄젠트

- np.deg2rad(array)  요소별 각도에서 라디안 변환
- np.rad2deg(array)  요소별 라디안에서 각도 변환
- np.hypot(array1, array2)  요소별 유클리드 거리 계산

In [81]:
t = np.linspace(0, np.pi, 3)
print(t)
print(np.sin(t))
print(np.cos(t))
print(np.tan(t))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


## 집계 함수(Aggregate Function)
- ### np.sum np.nansum 요소의 합 계산
- ### np.cumsum np.nancumsum 요소별 누적합
- ### np.diff N/A 요소의 차분
- ### np.prod np.nanprod 요소의 곱 계산
- ### np.cumprod np.nancumprod 요소의 누적 곱
- ### np.dot N/A 점 곱 (dot product)
- ### np.matmul N/A 행렬 곱 
- ### np.tensordot N/A 텐서곱 (tensor product)
- ### np.cross N/A 벡터곱(cross product)
- ### np.inner N/A 내적 (inner product)
- ### np.outer N/A 외적 (outer product)
- ### np.mean np.nanmean 요소의 평균
- ### np.std np.nanstd 표준 편차
- ### np.var np.nanvar 분산
- ### np.min np.nanmin 최소값
- ### np.max np.nanmax 최대값
- ### np.argmin np.nanargmin 최소값 인덱스
- ### np.argmax np.nanargmax 최대값 인덱스
- ### np.median np.nanmedian 중앙값
- ### np.percentile np.nanpercentile 요소의 순위 기반 백분위 수 계산
- ### np.any N/A 요소 중 참이 있는지 평가
- ### np.all N/A 모든 요소가 참인지 평가

- sum() : 합 계산

In [82]:
a2 = np.random.randint(1, 10, size=(3,3))
print(a2)
print(a2.sum(), np.sum(a2))
print(a2.sum(axis=0), np.sum(a2, axis=0))
print(a2.sum(axis=1), np.sum(a2, axis=1))

[[9 4 5]
 [9 4 7]
 [6 8 9]]
61 61
[24 16 21] [24 16 21]
[18 20 23] [18 20 23]


- cumsum() : 누적합 계산

In [83]:
print(a2)
print(a2.cumsum(), np.cumsum(a2))
print(a2.cumsum(axis=0), np.cumsum(a2, axis=0))
print(a2.cumsum(axis=1), np.cumsum(a2, axis=1))

[[9 4 5]
 [9 4 7]
 [6 8 9]]
[ 9 13 18 27 31 38 44 52 61] [ 9 13 18 27 31 38 44 52 61]
[[ 9  4  5]
 [18  8 12]
 [24 16 21]] [[ 9  4  5]
 [18  8 12]
 [24 16 21]]
[[ 9 13 18]
 [ 9 13 20]
 [ 6 14 23]] [[ 9 13 18]
 [ 9 13 20]
 [ 6 14 23]]


- diff() : 차분 계산

In [84]:
print(a2)
print(np.diff(a2))
print(np.diff(a2, axis=0))
print(np.diff(a2, axis=1))

[[9 4 5]
 [9 4 7]
 [6 8 9]]
[[-5  1]
 [-5  3]
 [ 2  1]]
[[ 0  0  2]
 [-3  4  2]]
[[-5  1]
 [-5  3]
 [ 2  1]]


- prod() : 곱 계산

In [85]:
print(a2)
print(np.prod(a2))
print(np.prod(a2, axis=0))
print(np.prod(a2, axis=1))

[[9 4 5]
 [9 4 7]
 [6 8 9]]
19595520
[486 128 315]
[180 252 432]


- cumprod() : 누적곱 계산

In [86]:
print(a2)
print(np.cumprod(a2))
print(np.cumprod(a2, axis=0))
print(np.cumprod(a2, axis=1))

[[9 4 5]
 [9 4 7]
 [6 8 9]]
[       9       36      180     1620     6480    45360   272160  2177280
 19595520]
[[  9   4   5]
 [ 81  16  35]
 [486 128 315]]
[[  9  36 180]
 [  9  36 252]
 [  6  48 432]]


- dot() / matmul() : 점 곱/행렬곱 계산

In [87]:
print(a2)
b2 = np.ones_like(a2)
print(b2)
print(np.dot(a2, b2))
print(np.matmul(a2, b2))

[[9 4 5]
 [9 4 7]
 [6 8 9]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[18 18 18]
 [20 20 20]
 [23 23 23]]
[[18 18 18]
 [20 20 20]
 [23 23 23]]


- tensordot() : 텐서곱 계산

In [88]:
print(a2)
print(b2)
print(np.tensordot(a2, b2))
print(np.tensordot(a2, b2, axes=0))
print(np.tensordot(a2, b2, axes=1))

[[9 4 5]
 [9 4 7]
 [6 8 9]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
61
[[[[9 9 9]
   [9 9 9]
   [9 9 9]]

  [[4 4 4]
   [4 4 4]
   [4 4 4]]

  [[5 5 5]
   [5 5 5]
   [5 5 5]]]


 [[[9 9 9]
   [9 9 9]
   [9 9 9]]

  [[4 4 4]
   [4 4 4]
   [4 4 4]]

  [[7 7 7]
   [7 7 7]
   [7 7 7]]]


 [[[6 6 6]
   [6 6 6]
   [6 6 6]]

  [[8 8 8]
   [8 8 8]
   [8 8 8]]

  [[9 9 9]
   [9 9 9]
   [9 9 9]]]]
[[18 18 18]
 [20 20 20]
 [23 23 23]]


- cross() : 벡터곱

In [89]:
x = [1,2,3]
y = [4,5,6]
print(np.cross(x, y))

[-3  6 -3]


- inner() / outer() : 내적/외적

In [90]:
print(a2)
print(b2)
print(np.inner(a2, b2))
print(np.outer(a2, b2))

[[9 4 5]
 [9 4 7]
 [6 8 9]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[18 18 18]
 [20 20 20]
 [23 23 23]]
[[9 9 9 9 9 9 9 9 9]
 [4 4 4 4 4 4 4 4 4]
 [5 5 5 5 5 5 5 5 5]
 [9 9 9 9 9 9 9 9 9]
 [4 4 4 4 4 4 4 4 4]
 [7 7 7 7 7 7 7 7 7]
 [6 6 6 6 6 6 6 6 6]
 [8 8 8 8 8 8 8 8 8]
 [9 9 9 9 9 9 9 9 9]]


- mean() : 평균 계산

In [91]:
print(a2)
print(np.mean(a2))
print(np.mean(a2, axis=0))
print(np.mean(a2, axis=1))

[[9 4 5]
 [9 4 7]
 [6 8 9]]
6.777777777777778
[8.         5.33333333 7.        ]
[6.         6.66666667 7.66666667]


- std() :표준편차 계산

In [92]:
print(a2)
print(np.std(a2))
print(np.std(a2, axis=0))
print(np.std(a2, axis=1))

[[9 4 5]
 [9 4 7]
 [6 8 9]]
1.9876159799998132
[1.41421356 1.88561808 1.63299316]
[2.1602469  2.05480467 1.24721913]


- var() : 분산 계산

In [93]:
print(a2)
print(np.var(a2))
print(np.var(a2, axis=0))
print(np.var(a2, axis=1))

[[9 4 5]
 [9 4 7]
 [6 8 9]]
3.9506172839506175
[2.         3.55555556 2.66666667]
[4.66666667 4.22222222 1.55555556]


- min() : 최소값

In [94]:
print(a2)
print(np.min(a2))
print(np.min(a2, axis=0))
print(np.min(a2, axis=1))

[[9 4 5]
 [9 4 7]
 [6 8 9]]
4
[6 4 5]
[4 4 6]


- max() : 최대값

In [95]:
print(a2)
print(np.max(a2))
print(np.max(a2, axis=0))
print(np.max(a2, axis=1))

[[9 4 5]
 [9 4 7]
 [6 8 9]]
9
[9 8 9]
[9 9 9]


- argmin() : 최소값 인덱스

In [96]:
print(a2)
print(np.argmin(a2))
print(np.argmin(a2, axis=0))
print(np.argmin(a2, axis=1))

[[9 4 5]
 [9 4 7]
 [6 8 9]]
1
[2 0 0]
[1 1 0]


- argmax() : 최대값 인덱스

In [97]:
print(a2)
print(np.argmax(a2))
print(np.argmax(a2, axis=0))
print(np.argmax(a2, axis=1))

[[9 4 5]
 [9 4 7]
 [6 8 9]]
0
[0 2 2]
[0 0 2]


- median() : 중앙값

In [98]:
print(a2)
print(np.median(a2))
print(np.median(a2, axis=0))
print(np.median(a2, axis=1))

[[9 4 5]
 [9 4 7]
 [6 8 9]]
7.0
[9. 4. 7.]
[5. 7. 8.]


- percentile() : 백분위 수

In [99]:
a1 = np.array([0,1,2,3])
print(a1)
print(np.percentile(a1, [0,20,40,60,80,100], interpolation='linear'))
print(np.percentile(a1, [0,20,40,60,80,100], interpolation='higher'))
print(np.percentile(a1, [0,20,40,60,80,100], interpolation='lower'))
print(np.percentile(a1, [0,20,40,60,80,100], interpolation='nearest'))
print(np.percentile(a1, [0,20,40,60,80,100], interpolation='midpoint'))

[0 1 2 3]
[0.  0.6 1.2 1.8 2.4 3. ]
[0 1 2 2 3 3]
[0 0 1 1 2 3]
[0 1 1 2 2 3]
[0.  0.5 1.5 1.5 2.5 3. ]


- any() : 요소 중 참이 있는지 평가

In [100]:
a2 = np.array([[False,False,False],[False,True,True],[False,True,True]])
print(a2)
print(np.any(a2))
print(np.any(a2, axis=0))
print(np.any(a2, axis=1))


[[False False False]
 [False  True  True]
 [False  True  True]]
True
[False  True  True]
[False  True  True]


- all() 모든 요소가 참 인지 평가

In [101]:
a2 = np.array([[False,False,False],[False,True,True],[True,True,True]])
print(a2)
print(np.all(a2))
print(np.all(a2, axis=0))
print(np.all(a2, axis=1))

[[False False False]
 [False  True  True]
 [ True  True  True]]
False
[False False False]
[False False  True]


## 비교 연산(Comparison Operators)

- ### '==' np.equal 
- ### '!=' np.not_equal
- ### '<' np.less
- ### '<=' np.less_equal
- ### '>' np.greater
- ### '>=' np.greater_equal

In [111]:
a1 = np.arange(1, 10)
print(a1)
print( a1 == 5)
a2 = np.array([[10, 5], [4, 8]])
print(a2)
print(np.sum(a2 <= 5))
print(np.sum(a2 <= 5, axis= 0))
print(np.sum(a2 <= 5, axis= 1))

[1 2 3 4 5 6 7 8 9]
[False False False False  True False False False False]
[[10  5]
 [ 4  8]]
2
[1 1]
[1 1]


- ### np.isclose 배열 두개가 (z*1e+02)% 내외로 가까우면 True, 아니면 False
- ### np.isinf 배열이 inf이면 True, 아니면 False
- ### np.isfinite 배열이 inf, nan이면 False, 아니면 True

In [113]:
a1 = np.array([1,2,3,4,5])
print(a1)
b1 = np.array([1,2,3,4,4])
print(b1)
print(np.isclose(a1, b1))

[1 2 3 4 5]
[1 2 3 4 4]
[ True  True  True  True False]


In [118]:
a1 = np.array([np.nan, 2, np.inf, 4, np.NINF])
print(a1)
print(np.isnan(a1))
print(np.isinf(a1))
print(np.isfinite(a1)) # 무한대가 아닌 것 !

[ nan   2.  inf   4. -inf]
[ True False False False False]
[False False  True False  True]
[False  True False  True False]


## 불리언 연산자 (Boolean Operators)

- ### '&' np.bitwise_and
- ### '|' np.bitwise_or
- ### '^' np.bitwise_xor
- ### '~' np.bitwise_not

In [121]:
a2 = np.arange(1, 10).reshape(3,3)
print(a2)

print((a2 > 5) & (a2 < 8))
print(a2[(a2 > 5) & (a2 < 8)])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False False False]
 [False False  True]
 [ True False False]]
[6 7]


In [124]:
print((a2 > 5) | (a2 < 8))
print(a2[(a2 > 5) | (a2 < 8)])

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[1 2 3 4 5 6 7 8 9]


In [125]:
print((a2 > 5) ^ (a2 < 8))
print(a2[(a2 > 5) ^ (a2 < 8)])

[[ True  True  True]
 [ True  True False]
 [False  True  True]]
[1 2 3 4 5 8 9]


In [128]:
print(~ (a2 > 5))
print(a2[~(a2 > 5)])

[[ True  True  True]
 [ True  True False]
 [False False False]]
[1 2 3 4 5]


## 배열 정렬
- ### sort()

In [131]:
a1 = np.random.randint(1, 10, size = 10)
print(a1)
print(np.sort(a1))
print(a1)
print(np.argsort(a1))
print(a1)
print(a1.sort())
print(a1)

[6 5 5 6 1 9 9 8 2 5]
[1 2 5 5 5 6 6 8 9 9]
[6 5 5 6 1 9 9 8 2 5]
[4 8 1 2 9 0 3 7 5 6]
[6 5 5 6 1 9 9 8 2 5]
None
[1 2 5 5 5 6 6 8 9 9]


In [132]:
a2 = np.random.randint(1, 10, size = (3,3))
print(a2)
print(np.sort(a2, axis=0))
print(np.sort(a2, axis=1))

[[4 8 2]
 [7 8 8]
 [6 7 9]]
[[4 7 2]
 [6 8 8]
 [7 8 9]]
[[2 4 8]
 [7 8 8]
 [6 7 9]]


## 부분정렬
- ### partition() : 배열에서 k개의 작은 값을 반환

In [135]:
a1 = np.random.randint(1, 10, size= 10)
print(a1)
print(np.partition(a1, 5))
print(np.partition(a1, 3))

[4 3 7 4 7 1 7 1 4 6]
[1 1 3 4 4 4 6 7 7 7]
[1 1 3 4 4 4 6 7 7 7]


## 배열 입출력
- ### np.save() Numpy 배열 객체 1개를 파일에 저장, 바이너리
- ### np.savez() Numpy 배열 객체 여러개를 파일에 저장, 바이너리
- ### np.load() Numpy 배열 저장 파일로 부터 객체 로딩, 바이너리
- ### np.loadtxt() 텍스트 파일로부터 배열 로딩, 텍스트
- ### np.savetxt() 텍스트 파일에 Numpy 배열 객체 저장, 텍스트

In [136]:
a2 = np.random.randint(1, 10, size = (5,5))
print(a2)
np.save("a", a2)

[[9 4 8 5 2]
 [4 3 2 6 9]
 [6 8 3 6 9]
 [5 5 5 5 4]
 [9 6 8 7 5]]


In [138]:
!dir a*
# 2022-04-05 (화)  오전 08:49               228 a.npy

 D 드라이브의 볼륨: 새 볼륨
 볼륨 일련 번호: 308C-A885

 D:\temp 디렉터리

2022-04-05 (화)  오전 08:49               228 a.npy
               1개 파일                 228 바이트
               0개 디렉터리  180,783,865,856 바이트 남음


In [139]:
b2 = np.random.randint(1, 10, size = (5,5))
print(b2)
np.savez('ab', a2, b2)

[[6 5 8 9 6]
 [8 3 4 4 9]
 [9 2 1 6 9]
 [3 9 8 8 3]
 [9 2 6 1 7]]


In [140]:
!dir a*
# 2022-04-05 (화)  오전 08:49               228 a.npy
# 2022-04-05 (화)  오전 08:50               706 ab.npz

 D 드라이브의 볼륨: 새 볼륨
 볼륨 일련 번호: 308C-A885

 D:\temp 디렉터리

2022-04-05 (화)  오전 08:49               228 a.npy
2022-04-05 (화)  오전 08:50               706 ab.npz
               2개 파일                 934 바이트
               0개 디렉터리  180,783,865,856 바이트 남음


In [141]:
npy = np.load('a.npy')
print(npy)

[[9 4 8 5 2]
 [4 3 2 6 9]
 [6 8 3 6 9]
 [5 5 5 5 4]
 [9 6 8 7 5]]


In [143]:
npz = np.load('ab.npz')
print(npz.files)

['arr_0', 'arr_1']


In [144]:
print(npz['arr_0'])
print(npz['arr_1'])

[[9 4 8 5 2]
 [4 3 2 6 9]
 [6 8 3 6 9]
 [5 5 5 5 4]
 [9 6 8 7 5]]
[[6 5 8 9 6]
 [8 3 4 4 9]
 [9 2 1 6 9]
 [3 9 8 8 3]
 [9 2 6 1 7]]


In [145]:
np.savetxt('a.csv', a2, delimiter=',')

In [146]:
!dir a*

 D 드라이브의 볼륨: 새 볼륨
 볼륨 일련 번호: 308C-A885

 D:\temp 디렉터리

2022-04-05 (화)  오전 09:30               630 a.csv
2022-04-05 (화)  오전 08:49               228 a.npy
2022-04-05 (화)  오전 08:50               706 ab.npz
               3개 파일               1,564 바이트
               0개 디렉터리  180,783,861,760 바이트 남음


In [147]:
!more a.csv

9.000000000000000000e+00,4.000000000000000000e+00,8.000000000000000000e+00,5.000000000000000000e+00,2.000000000000000000e+00
4.000000000000000000e+00,3.000000000000000000e+00,2.000000000000000000e+00,6.000000000000000000e+00,9.000000000000000000e+00
6.000000000000000000e+00,8.000000000000000000e+00,3.000000000000000000e+00,6.000000000000000000e+00,9.000000000000000000e+00
5.000000000000000000e+00,5.000000000000000000e+00,5.000000000000000000e+00,5.000000000000000000e+00,4.000000000000000000e+00
9.000000000000000000e+00,6.000000000000000000e+00,8.000000000000000000e+00,7.000000000000000000e+00,5.000000000000000000e+00


In [148]:
csv = np.loadtxt('a.csv', delimiter=',')
print(csv)

[[9. 4. 8. 5. 2.]
 [4. 3. 2. 6. 9.]
 [6. 8. 3. 6. 9.]
 [5. 5. 5. 5. 4.]
 [9. 6. 8. 7. 5.]]


In [149]:
np.savetxt('b.csv', b2, delimiter=',', fmt='%.2e', header='c1, c2, c3, c4, c5')

In [150]:
!dir b*

 D 드라이브의 볼륨: 새 볼륨
 볼륨 일련 번호: 308C-A885

 D:\temp 디렉터리

2022-04-05 (화)  오전 09:32               252 b.csv
               1개 파일                 252 바이트
               0개 디렉터리  180,783,861,760 바이트 남음


In [151]:
!more b.csv

# c1, c2, c3, c4, c5
6.00e+00,5.00e+00,8.00e+00,9.00e+00,6.00e+00
8.00e+00,3.00e+00,4.00e+00,4.00e+00,9.00e+00
9.00e+00,2.00e+00,1.00e+00,6.00e+00,9.00e+00
3.00e+00,9.00e+00,8.00e+00,8.00e+00,3.00e+00
9.00e+00,2.00e+00,6.00e+00,1.00e+00,7.00e+00


In [152]:
csv = np.loadtxt('b.csv', delimiter=',')
print(csv)

[[6. 5. 8. 9. 6.]
 [8. 3. 4. 4. 9.]
 [9. 2. 1. 6. 9.]
 [3. 9. 8. 8. 3.]
 [9. 2. 6. 1. 7.]]
